const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

const TIMEOUT_MS = 35 * 60 * 1000; // 35 minutes hard cap
const HOME = process.env.HOME || process.env.USERPROFILE;
const SKILL_PATH = path.join(HOME, '.claude', 'skills', 'serenity', 'skill.md');

function runAnalysis(stock, onProgress) {
  return new Promise((resolve, reject) => {
    if (!fs.existsSync(SKILL_PATH)) {
      reject(new Error(`Serenity 技能文件未找到: ${SKILL_PATH}`));
      return;
    }

    const prompt = [
      `你将对上市公司「${stock}」执行 Serenity 瓶颈点投资分析全流程 (v2.9.1)。该标的可能来自 A 股（沪深北）、港股或美股市场。请根据股票代码/名称自动判断市场，并使用对应市场的估值体系和数据源。若为 A+H 双上市标的，需分别建模各市场数据并做 sum-of-parts 聚合。`,
      ``,
      `【⚠️ 最重要指令 — 输出要求】`,
      `你的完整 stdout 输出就是最终报告本身——没有任何后续润色环节。`,
      `因此你必须把以下所有内容原封不动地写在输出里：`,
      `- 每个 Stage 的完整搜索过程（搜索了什么关键词、找到了什么数据、数据来源 URL + 抓取时间）`,
      `- 每个 Stage 的完整分析推理（不是摘要，是完整的推理论证段落）`,
      `- 每个 Stage 的规定表格（表格行数必须达标，不能缩水）`,
      `- 每个 Stage 的 "## Stage N: xxx" 标题和 "✅ Stage N 完成" 结尾标记`,
      `- 所有关键数据标注 [VERIFIED]/[UNVERIFIED]/[INFERRED] + 来源 URL`,
      ``,
      `总输出需达到 5000 字以上。禁止输出浓缩摘要。禁止使用"（详见上文）""（同上）""（略）"。`,
      ``,
      `【强制结构 — 必须按此顺序，一个都不能少】`,
      ``,
      `## Stage 1: 产业链瓶颈映射 (chokepoint-map)`,
      ``,
      `### 1.1 产业链结构调研`,
      `搜索至少 3 次，覆盖该公司所处行业的上下游环节。列出每个搜索的关键词和获取到的信息。`,
      ``,
      `### 1.2 产业链各环节分析`,
      `对上游、中游、下游每个环节逐一分析：该环节做什么、有哪些公司、集中度如何、进入壁垒多高。`,
      ``,
      `### 1.3 瓶颈定位`,
      `指出该产业链中哪个环节构成最强制约——供给集中、认证壁垒高、客户切换成本大。解释为什么。`,
      ``,
      `### 1.4 瓶颈环节供应商清单`,
      `列出该瓶颈环节的所有主要供应商，含市场份额估计、技术路线、主要客户。表格不少于 3 行。`,
      ``,
      `| 供应商名称 | 市场份额 | 技术路线/产品 | 主要客户 | 竞争优势 | 来源 URL |`,
      `|-----------|---------|-------------|---------|---------|----------|`,
      ``,
      `### 1.5 瓶颈评级`,
      `最终瓶颈等级（Hard / Medium / Soft），瓶颈评分（1-4分）。`,
      `⚠️ Hard gate: 若瓶颈评分 < 2，报告终止，输出"⛔ 瓶颈评分不足，不构成可投资瓶颈"。`,
      ``,
      `✅ Stage 1 完成`,
      ``,
      `## Stage 2: 六因子打分卡 (five-factor-score)`,
      ``,
      `对每一因子，先搜索相关数据，再给出整数评分和详细理由（每项不少于 5 句分析）。`,
      `⚠️ v2.9 整数约束：所有因子分数必须是整数（1-5）。Adj Score = round(Raw × F6 倍数)。`,
      ``,
      `### F1a 护城河广度（1-5分，整数）`,
      `搜索该瓶颈环节的全球供应商数量和替代关系。分析：有多少替代供应商？新进入者需要多久才能形成有效竞争？`,
      ``,
      `### F1b 护城河深度（1-5分，整数）`,
      `搜索新供应商认证周期和客户切换成本。分析：下游客户更换供应商需要多长时间认证？切换过程中的风险是什么？`,
      ``,
      `### F2 需求持续性（1-5分，整数）`,
      `搜索下游需求趋势、行业增速、技术替代风险。分析：该瓶颈对应的下游需求是否具有 10 年以上的持续性？`,
      ``,
      `### F3 需求弹性/价值捕获（1-5分，整数）`,
      `搜索该公司的收入增长与下游需求增长的匹配度。分析：下游爆发时，该公司能否同比例受益？有没有收入漏出的环节？`,
      ``,
      `### F4 定价权与盈利能力（1-5分，整数）`,
      `⚠️ v2.7.5 F4 证据要求：搜索并列出全部 8 项数据（股价、股数、市值、营收、净利、PS、PE(FY)、PE(TTM)），每项附来源 URL。`,
      `必须包含以下数据表格：`,
      ``,
      `| 财务指标 | 最新报告期数值 | 同比变动 | 行业平均水平 | 来源 URL |`,
      `|---------|-------------|---------|------------|----------|`,
      `| 毛利率 | XX% | +/-XX% | XX% | [url] |`,
      `| 净利率 | XX% | +/-XX% | XX% | [url] |`,
      `| ROE | XX% | +/-XX% | XX% | [url] |`,
      `| ROIC | XX% | +/-XX% | XX% | [url] |`,
      `| 营收增长率 | XX% | +/-XX% | XX% | [url] |`,
      `| 净利增长率 | XX% | +/-XX% | XX% | [url] |`,
      `| 经营现金流/净利 | XX% | — | — | [url] |`,
      ``,
      `基于数据逐一分析：毛利率是否 >40%？FCF/净利比率是否健康？是否具备持续提价能力？`,
      ``,
      `### F5 管理层质量（1-5分，整数）`,
      `搜索管理层背景、历史资本配置记录、分红/回购记录、有无诚信问题。分析其资本配置能力和股东回报意愿。`,
      ``,
      `### F6 估值安全边际（1-5分，整数）`,
      `根据市场类型调整：A 股查 PE(TTM)/PB 及历史分位；美股查 P/S、FCF Yield、PEG；港股结合两者。`,
      `搜索当前估值数据，对比历史区间和行业平均。分析当前估值是否提供安全边际。`,
      ``,
      `### 2.X 六因子汇总`,
      ``,
      `| 因子 | 分数 | 关键判断 | 来源 URL | 证据可信度 |`,
      `|------|------|---------|----------|-----------|`,
      `| F1a 护城河广度 | X/5 | [判断] | [url] | [VERIFIED/UNVERIFIED/INFERRED] |`,
      `| F1b 护城河深度 | X/5 | [判断] | [url] | [VERIFIED/UNVERIFIED/INFERRED] |`,
      `| F2 需求持续性 | X/5 | [判断] | [url] | [VERIFIED/UNVERIFIED/INFERRED] |`,
      `| F3 价值捕获 | X/5 | [判断] | [url] | [VERIFIED/UNVERIFIED/INFERRED] |`,
      `| F4 定价权 | X/5 | [判断] | [url] | [VERIFIED/UNVERIFIED/INFERRED] |`,
      `| F5 管理层 | X/5 | [判断] | [url] | [VERIFIED/UNVERIFIED/INFERRED] |`,
      `| F6 估值安全边际 | X/5 | [判断] | [url] | [VERIFIED/UNVERIFIED/INFERRED] |`,
      `| **Raw Score** | **XX/30** | | | |`,
      `| **F6 倍数** | **X.X×** | | | |`,
      `| **Adj Score** | **XX** | = round(Raw × F6) | | |`,
      ``,
      `✅ Stage 2 完成`,
      ``,
      `## R2: 评分审查 (平行于 Stage 2.5)`,
      ``,
      `Q1-Q4 逐项审查：`,
      ``,
      `| 因子 | 原始分 | 审查意见 | 修正分 | 修正理由 |`,
      `|------|--------|---------|--------|----------|`,
      `| F1a | X | [意见] | X / 不变 | [理由] |`,
      `| F1b | X | [意见] | X / 不变 | [理由] |`,
      `| F2 | X | [意见] | X / 不变 | [理由] |`,
      `| F3 | X | [意见] | X / 不变 | [理由] |`,
      `| F4 | X | [意见] | X / 不变 | [理由] |`,
      `| F5 | X | [意见] | X / 不变 | [理由] |`,
      `| F6 | X | [意见] | X / 不变 | [理由] |`,
      ``,
      `Q4 来源可验证性：N/7 因子通过验证，评级 [GREEN/AMBER/RED]`,
      `FLAGS = [无修正 / 部分修正 / 重大修正]`,
      ``,
      `✅ R2 完成`,
      ``,
      `## Stage 2.5: 交叉验证 + 一致性检查`,
      ``,
      `### 财务数据验证`,
      `搜索至少 2 个来源验证 F4 所用财务数据。A+H 标的需分别验证各市场数据。`,
      ``,
      `| 数据项 | Stage 2 使用值 | 验证值 | 来源 | 抓取时间 | 一致？ |`,
      `|--------|-------------|--------|------|----------|--------|`,
      `| 股价 | ¥XX | ¥XX | [url] | [timestamp] | ✅/⚠️ |`,
      `| 总市值 | ¥XX亿 | ¥XX亿 | [url] | [timestamp] | ✅/⚠️ |`,
      `| 年度营收 | ¥XX亿 | ¥XX亿 | [url] | [timestamp] | ✅/⚠️ |`,
      `| 年度净利 | ¥XX亿 | ¥XX亿 | [url] | [timestamp] | ✅/⚠️ |`,
      `| PS | XX× | XX× | 计算 | — | ✅/⚠️ |`,
      `| PE(TTM) | XX× | XX× | 计算 | — | ✅/⚠️ |`,
      ``,
      `### 行业报告验证`,
      `搜索券商研报或行业分析，交叉验证瓶颈判断。`,
      ``,
      `### 竞争格局验证`,
      `搜索主要竞争对手财务数据横向对比。`,
      ``,
      `| 公司 | 市值 | 毛利率 | 净利率 | ROE | 营收增速 | PE | 来源 |`,
      `|------|------|--------|--------|-----|---------|-----|------|`,
      ``,
      `### Conflict Resolution`,
      `R2 修正与 Stage 2.5 发现合并，输出 COHERENT/MINOR_DIFF/MAJOR_DIFF。`,
      ``,
      `✅ Stage 2.5 完成`,
      ``,
      `## Stage 2.6: 机械验证 ⚠️ v2.9.1`,
      ``,
      `⚠️ v2.9.1 双市场支持：A+H 标的需分别报告各市场 listings 数据（price/shares/market_cap），`,
      `以及 total_market_cap 聚合层和 fx_rates。`,
      ``,
      `输出验证输入 JSON 并运行：`,
      `python ~/.claude/scripts/verify_serenity.py --input verify_input_<ticker>_<date>.json`,
      ``,
      `检查项：`,
      `- A1: market_cap = price × shares（每个活跃 listing）`,
      `- A2: PS = market_cap / revenue`,
      `- A3: PE = market_cap / net_income`,
      `- A5: sum-of-parts total ≡ Σ(market_cap × fx)（A+H 双市场）`,
      `- A6: 汇率一致性 + HKD_CNY ∈ [0.80,0.95]`,
      `- B: 整数分约束（所有因子分为整数）`,
      `- C: COHERENT ↔ segment-data 一致性`,
      `- D: 置信度公式 valid`,
      `- E: 来源可验证性比率`,
      ``,
      `| 检查 | 状态 | 详情 |`,
      `|------|------|------|`,
      `| A1 (price×shares) | ✅/❌ | |`,
      `| A2 (PS) | ✅/❌ | |`,
      `| A3 (PE) | ✅/❌ | |`,
      `| A5 (sum-of-parts) | ✅/❌/N/A | |`,
      `| A6 (FX) | ✅/❌/N/A | |`,
      `| B (integer scores) | ✅/❌ | |`,
      `| C (coherence) | ✅/❌ | |`,
      `| D (confidence) | ✅/❌ | |`,
      `| E (source ratio) | ✅/⚠️ | |`,
      ``,
      `⚠️ HARD 失败 → 返回 Stage 2 重算。SOFT 失败 → 标记但继续。`,
      ``,
      `✅ Stage 2.6 完成`,
      ``,
      `## Pre-R3: Delta 阈值检测 + R3`,
      ``,
      `计算 max(|Stage 2 原始分 − Stage 2.5 修正分|)。`,
      `若 max_delta ≤ 1 → 跳过 R3，说明原因。`,
      `若 max_delta ≥ 2 或 SEVERE GAP → 触发 R3，逐项修正并输出完整六因子表。`,
      ``,
      `✅ R3 完成 / ⏭️ R3 跳过`,
      ``,
      `## Confidence Scoring`,
      ``,
      `| 标志 | 状态 | 罚分 |`,
      `|------|------|------|`,
      `| 来源验证缺口 | [Y/N] | -X |`,
      `| 多源不一致 | [Y/N] | -X |`,
      `| 估值数据过期 | [Y/N] | -X |`,
      `| 行业数据未验证 | [Y/N] | -X |`,
      `| 管理层信息二手 | [Y/N] | -X |`,
      `| F4 UNVERIFIED | [Y/N] | -X |`,
      ``,
      `Confidence = Adj − Σpenalty (底限 Adj−15)。`,
      `Tier: ≥21 = FULL, 18-20 = STANDARD, 15-17 = CAUTIOUS (elevated scrutiny), <15 = DEGRADED。`,
      ``,
      `✅ Confidence 计算完成`,
      ``,
      `## Stage 3.5 Phase A: 关联预计算（与 Stage 3 并行）`,
      ``,
      `计算与同业/上下游标的的关联性（供应链共用、终端客户重合、技术路径相关），`,
      `输出 top-3 关联对发给 Stage 3 红方/蓝方做参考。`,
      ``,
      `| 关联对 | 类型 | 关联强度 |`,
      `|--------|------|---------|`,
      ``,
      `## Stage 3: 红蓝对抗 ∥ ⚡ market-structure-check (v2.8)`,
      ``,
      `⚠️ 红蓝对抗使用 confidence-based 分层深度。`,
      ``,
      `### 3.0 Market Structure Audit (v2.8 — 并行于辩论)`,
      ``,
      `**Module A: 量价动态**`,
      `- 近 20 日/60 日量价关系`,
      `- 换手率 vs 区间涨跌幅`,
      `- 异常量价信号`,
      ``,
      `**Module B: 筹码集中度**`,
      `- 股东户数变化趋势`,
      `- 前十大股东持股比例`,
      `- 机构/散户持仓变化`,
      ``,
      `**Module C: 特殊风险标记**`,
      `- 庄股检测（市值<50亿 + 多因子评分 max 12分）`,
      `- ST/退市风险`,
      `- 解禁时间表`,
      `- 重要股东减持`,
      `- 股权质押比例`,
      `- 商誉减值风险`,
      ``,
      `| 风险维度 | 状态 | 风险等级 |`,
      `|---------|------|---------|`,
      `| 庄股嫌疑 | [评分/12] | [低/中/高] |`,
      `| ST/退市 | [Y/N] | — |`,
      `| 近期解禁 | [日期/规模] | [影响评估] |`,
      `| 股东减持 | [有/无] | — |`,
      `| 股权质押 | [X%] | — |`,
      `| 商誉 | [X亿/X%] | — |`,
      ``,
      `⚠️ 非 A 股市场：Module C 部分跳过，标注"非A股，部分检测不适用"。`,
      ``,
      `### 🔴 红方（多头）`,
      `列出至少 5 条做多理由，每条附具体数据、来源和推理：`,
      `1. [理由] — 数据: [xxx], 来源: [url]`,
      `2. ...`,
      ``,
      `### 🔵 蓝方（空头）`,
      `列出至少 5 条做空/风险理由，每条附具体数据、来源和推理：`,
      `1. [理由] — 数据: [xxx], 来源: [url]`,
      `2. ...`,
      ``,
      `### 辩论裁决`,
      `红蓝核心分歧。Survivability 评分（1-10）及理由。`,
      ``,
      `✅ Stage 3 完成`,
      ``,
      `## Stage 3.5 Phase B: 仓位校准（含市场结构风控）`,
      ``,
      `### 基准仓位表`,
      ``,
      `| 因子 | 得分/评级 | 基准仓位 | 调整幅度 | 调整原因 |`,
      `|------|---------|---------|---------|----------|`,
      `| 瓶颈实力度 | X/4 | X% | +/-X% | [原因] |`,
      `| 六因子 Adj | XX | X% | +/-X% | [原因] |`,
      `| Survivability | X/10 | X% | +/-X% | [原因] |`,
      `| 市场环境 | [判断] | X% | +/-X% | [原因] |`,
      `| **基本面仓位** | | | **X%** | |`,
      ``,
      `### 市场结构风控上限（v2.8）`,
      ``,
      `| 风险标签 | 仓位上限 | 适用？ |`,
      `|---------|---------|--------|`,
      `| [ST/退市/高度庄股] | 0% | [Y/N] |`,
      `| [庄股嫌疑] | 3% | [Y/N] |`,
      `| [解禁/减持] | 基本仓位减半 | [Y/N] |`,
      ``,
      `| **最终建议仓位** | | | **X%** | |`,
      ``,
      `✅ Stage 3.5 完成`,
      ``,
      `## Stage 4: 最终投资报告`,
      ``,
      `### 4.1 标的信息`,
      `- 公司全称 / 代码 / 上市市场 / 所属行业`,
      `- 若 A+H 双上市：分别列出 A 股和 H 股信息`,
      ``,
      `### 4.2 核心投资逻辑（不少于 8 句话）`,
      `用完整段落阐述投资逻辑，涵盖：瓶颈地位、财务质量、估值水平、成长驱动、风险对冲。`,
      ``,
      `### 4.3 建议仓位与持有期`,
      `[X%] 仓位，建议持有 [X-Y 个月]，目标价 ¥[XX]，止损价 ¥[XX]。`,
      ``,
      `### 4.4 关键风险（不少于 5 个）`,
      `1. [风险] — [触发条件] — [影响预估]`,
      `2. ...`,
      ``,
      `### 4.5 关键观察节点`,
      `未来 6-12 个月需跟踪的事件：`,
      `1. [时间] — [事件] — [观察指标]`,
      `2. ...`,
      ``,
      `### 4.6 Section 7: Market Structure Audit (v2.8)`,
      `整合 Stage 3 并行审计结果，列出量价、筹码、风险标记的关键发现及仓位影响。`,
      ``,
      `### 4.7 Model Provenance`,
      ``,
      `| Stage | 模型 | 用途 |`,
      `|-------|------|------|`,
      `| Stage 1-4 | Claude (主模型) | 全流程分析 |`,
      `| R2 | opencode-standalone | 评分审查 |`,
      `| Stage 2.6 | Python verify_serenity.py | 机械算术验证 |`,
      `| R3 | opencode-standalone | 重验证(条件触发) |`,
      `| Stage 3 蓝方 | opencode-bridge (GLM) | 独立空头视角 |`,
      `| market-structure-check | Claude (主模型) | 量价/筹码/风险审计 |`,
      `| R7 Tier 1 | 机械脚本 | URL/时间戳/可信度扫描 |`,
      `| R7 Tier 2 | opencode-bridge (GLM) | 独立风控终审 |`,
      ``,
      `✅ Stage 4 完成`,
      ``,
      `## R7: 冷阅终审 (Tier 1 机械 + Tier 2 判断)`,
      ``,
      `### Tier 1: 机械检查`,
      `- URL 数量统计（每阶段 ≥ 2 个来源 URL）`,
      `- 时间戳新鲜度（财务数据 ≤ 1 个报告期）`,
      `- VERIFIED 比率（≥ 60% 数据点为 VERIFIED）`,
      ``,
      `### Tier 2: 判断审查`,
      `1. **数据可验证性**：每条核心结论是否都有可追溯的搜索数据支撑？缺失项列出。`,
      `2. **确认偏误检查**：分析过程中是否存在先入为主的假设？`,
      `3. **最脆弱假设**：整个投资逻辑中，哪个假设如果被证伪，整个逻辑链会断裂？`,
      `4. **极端回撤预估**：在最坏情景下，该标的可能回撤多少？理由是什么？`,
      ``,
      `| 审查项 | 评定 | 说明 |`,
      `|--------|------|------|`,
      `| 数据完整性 | X/10 | [说明] |`,
      `| 逻辑一致性 | X/10 | [说明] |`,
      `| 反方覆盖度 | X/10 | [说明] |`,
      `| 估值合理性 | X/10 | [说明] |`,
      `| **Quality Score** | **X/10** | DEGRADED / PASS / PASS WITH FLAGS / EXCELLENT |`,
      ``,
      `✅ R7 完成`,
      ``,
      `---`,
      `## 📊 最终汇总`,
      ``,
      `| 维度 | 结果 |`,
      `|------|------|`,
      `| 标的 | 「${stock}」 |`,
      `| 市场 | [A股/港股/美股/A+H] |`,
      `| 瓶颈等级 | [Hard/Medium/Soft] — X/4 |`,
      `| 六因子 Raw | XX/30 |`,
      `| 六因子 Adj | XX |`,
      `| Confidence | XX (Tier: FULL/STANDARD/CAUTIOUS/DEGRADED) |`,
      `| 辩论 Survivability | X/10 |`,
      `| 市场结构风险 | [无/庄股嫌疑/解禁/减持/ST] |`,
      `| 建议仓位 | X% |`,
      `| R7 Quality | X/10 — [PASS/EXCELLENT/DEGRADED] |`,
      ``,
      `⚠️ 本报告由 AI 自动生成，不构成投资建议。请结合自身情况独立判断。`,
    ].join('\n');

    const env = {
      ...process.env,
      HTTP_PROXY: 'http://127.0.0.1:15236',
      HTTPS_PROXY: 'http://127.0.0.1:15236',
    };

    const args = [
      '-p', prompt,
      '--system-prompt-file', SKILL_PATH,
      '--output-format', 'text',
      '--effort', 'high',
    ];

    const child = spawn('claude', args, {
      env,
      shell: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      cwd: HOME,
    });

    let stdout = '';
    let stderr = '';
    let resolved = false;
    const startTime = Date.now();

    // Progress simulation: update every 30s based on elapsed time
    onProgress('正在分析（搜索产业链数据...）', 5);
    const progressTimer = setInterval(() => {
      const elapsed = (Date.now() - startTime) / 1000;
      const totalExpected = 900; // roughly 15 minutes expected for detailed analysis
      const pct = Math.min(88, 5 + (elapsed / totalExpected) * 83);
      const min = Math.floor(elapsed / 60);
      const sec = Math.floor(elapsed % 60);
      onProgress(`分析中... 已耗时 ${min}分${sec}秒`, Math.round(pct));
    }, 30000);

    // ----- Hard timeout -----
    const hardTimer = setTimeout(() => {
      if (resolved) return;
      child.kill('SIGTERM');
      reject(new Error('分析超时（超过 25 分钟），请重试'));
      resolved = true;
    }, TIMEOUT_MS);

    // ----- Stdout (buffered in -p mode, arrives at the end) -----
    child.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    child.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    child.on('close', (code) => {
      if (resolved) return;
      resolved = true;
      clearInterval(progressTimer);
      clearTimeout(hardTimer);

      if (code === 0) {
        resolve({ markdown: stdout });
      } else {
        const errMsg = stderr.slice(-500) || `CLI exited with code ${code}`;
        reject(new Error(`分析引擎中断: ${errMsg}`));
      }
    });

    child.on('error', (err) => {
      if (resolved) return;
      resolved = true;
      clearInterval(progressTimer);
      clearTimeout(hardTimer);
      reject(new Error(`无法启动 Claude CLI: ${err.message}`));
    });
  });
}

module.exports = { runAnalysis };
